import SyncFusion from "../SyncFusion"
import expand from "./expand";

export let columnDefProject: any[] = [
  {
    headerName: "fsd ",
    field: "customerOrProject",
    cellRenderer: expand
  },
  {
    headerName: "jan",
    field: "jan",
  },
  {
    headerName: "feb",
    field: "feb",
  },
  {
    headerName: "mar",
    field: "mar",
  },
];
export let rowDataProject: any[] = [
  {
    customerOrProject: "CasaPerks",
    jan: 0,
    feb: 0,
    mar: 0,
    children: [
      {
        customerOrProject: "Parth",
        jan: 100,
        feb: 100,
        mar: 100,
      },
      {
        customerOrProject: "Harsh",
        jan: 100,
        feb: 100,
        mar: 100,
      },
      {
        customerOrProject: "Vivek",
        jan: 100,
        feb: 100,
        mar: 100,
      },
    ],
  },
  {
    customerOrProject: "Intelerad-Ambra",
    jan: 0,
    feb: 0,
    mar: 0,
    children: [
      {
        customerOrProject: "Kiran",
        jan: 100,
        feb: 100,
        mar: 100,
      },
      {
        customerOrProject: "Ajay",
        jan: 100,
        feb: 100,
        mar: 100,
      },
      {
        customerOrProject: "Karan",
        jan: 100,
        feb: 100,
        mar: 100,
      },
    ],
  }
];
export let projectData: any[] = [
  {
    customerOrProject: "Intelerad",
    dec: "",
    nov: "",
    oct: "",
    sep: "",
    aug: "",
    jul: "",
    jun: "",
    may: "",
    apr: "",
    mar: "",
    feb: "",
    jan: "",
    children: [
      {
        customerOrProject: "Ambra-DB-migration",
        dec: "",
        nov: "",
        oct: "",
        sep: "",
        aug: "",
        jul: "",
        jun: "",
        may: "",
        apr: "",
        mar: "",
        feb: "",
        jan: "",
        children: [
          {
            customerOrProject: "Parth",
            dec: "0",
            nov: "0",
            oct: "0",
            sep: "0",
            aug: "100",
            jul: "100",
            jun: "100",
            may: "100",
            apr: "100",
            mar: "100",
            feb: "100",
            jan: "100",
          },
          {
            customerOrProject: "Harsh",
            dec: "0",
            nov: "50",
            oct: "100",
            sep: "100",
            aug: "100",
            jul: "100",
            jun: "100",
            may: "100",
            apr: "100",
            mar: "100",
            feb: "100",
            jan: "100",
          },
        ],
      },
      {
        customerOrProject: "Ambra-storage",
        dec: "",
        nov: "",
        oct: "",
        sep: "",
        aug: "",
        jul: "",
        jun: "",
        may: "",
        apr: "",
        mar: "",
        feb: "",
        jan: "",
        children: [
          {
            customerOrProject: "Kiran",
            dec: "0",
            nov: "0",
            oct: "0",
            sep: "0",
            aug: "100",
            jul: "100",
            jun: "100",
            may: "100",
            apr: "100",
            mar: "100",
            feb: "100",
            jan: "100",
          },
          {
            customerOrProject: "Vivek",
            dec: "0",
            nov: "50",
            oct: "100",
            sep: "100",
            aug: "100",
            jul: "100",
            jun: "100",
            may: "100",
            apr: "100",
            mar: "100",
            feb: "100",
            jan: "100",
          },
        ],
      },
    ],
  },
];
